#!/bin/bash

# House Keeping
if [ ! -d "$HOME/.backup" ]; then
	mkdir $HOME/.backup
fi
cd $HOME/.backup

# Backup Root Partition
sudo tar -cvpzf $HOME/.backup/backup-root-$(uname -n)-$(date +%s).tar.gz --exclude={"backup-*.tar.gz","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} --one-file-system /
