#!/usr/bin/env bash

# House Keeping
_BACKUP_DIR="${HOME}/data/.backup"
if [ ! -d "${_BACKUP_DIR}" ]; then
	mkdir -p "${_BACKUP_DIR}"
fi
cd "${_BACKUP_DIR}"

# Backup Root Partition
sudo tar -cvpzf "${_BACKUP_DIR}/backup-root-$(uname -n)-$(date +%s).tar.gz" --exclude={"backup-*.tar.gz","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} --one-file-system /
