#!/usr/bin/env bash

# House Keeping
_BACKUP_DIR="${HOME}/data/.backup"
if [ ! -d "${_BACKUP_DIR}" ]; then
	mkdir -p "${_BACKUP_DIR}"
fi
cd "${_BACKUP_DIR}"

# Backup EFI System Partition
sudo tar -cvzf "${_BACKUP_DIR}/backup-esp-$(uname -n)-$(date +%s).tar.gz" /boot/efi
