#!/usr/bin/env bash

# House Keeping
BACKUP_DIR="${HOME}/.backup"
if [ ! -d "${BACKUP_DIR}" ]; then
	mkdir -p "${BACKUP_DIR}"
fi
cd "${BACKUP_DIR}"

# Backup EFI System Partition
sudo tar -cvzf "${BACKUP_DIR}/backup-esp-$(uname -n)-$(date +%s).tar.gz" /boot/efi
