#!/usr/bin/env bash

set -euo pipefail

declare -r list_file="${XDG_CONFIG_HOME:-"${HOME}/.config"}/personal/default_node_global_packages"

if ! test -f "${list_file}"; then
  echo "missing config file: ${list_file}" >&2
  exit 2
fi

if ! type node >/dev/null 2>&1; then
  echo "missing command: node" >&2
  exit 1
fi

if ! type npm >/dev/null 2>&1; then
  echo "missing command: npm" >&2
  exit 1
fi

declare -a packages
mapfile -t packages < <(cat "${list_file}")

echo "node version : $(node --version)"
echo "npm version  : $(npm --version)"
echo
echo "default global packages:"
echo
printf -- "- %s\n" "${packages[@]}"
echo

npm install --global "${packages[@]}"
