#!/usr/bin/env sh

EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
  >&2 echo 'ERROR: Invalid installer signature'
  rm composer-setup.php
  exit 1
fi

INSTALL_DIR=${_USER_BIN:-$HOME/.local/bin}

php composer-setup.php --quiet --install-dir="${INSTALL_DIR}" --filename=composer
RESULT=$?
rm composer-setup.php
exit $RESULT

