#!/usr/bin/env bash

# install/update tmux plugin manager
# https://github.com/tmux-plugins/tpm

_tpm_dir="${HOME}/.tmux/plugins/tpm"

if [[ -d "${_tpm_dir}" ]]; then
  (
    echo "tpm is already installed!"
    echo "Updating tpm..."
    cd "${_tpm_dir}"
    git pull
  )
else
  (
    echo "Installing tpm..."
    git clone https://github.com/tmux-plugins/tpm "${_tpm_dir}"
  )
fi
