#!/usr/bin/env bash

set -eu

get_latest_reposiotry() {
  local repo_uri="${1}"
  local repo_dir="${2}"

  echo "Repository URI: ${repo_uri}"
  if [[ ! -d "${repo_dir}" ]]; then
    echo "Cloning repository..."
    mkdir -p "$(dirname "${repo_dir}")"
    git clone --quiet --recursive "${repo_uri}" "${repo_dir}"
    pushd "${repo_dir}" >/dev/null
  else
    echo "Pulling latest commits..."
    pushd "${repo_dir}" >/dev/null
    git pull
    git submodule update --init
  fi

  popd >/dev/null
}

declare -r owner="alacritty"
declare -r repo="alacritty"

get_latest_reposiotry "https://github.com/${owner}/${repo}" "${HOME}/Dev/github/${owner}/${repo}"
pushd "${HOME}/Dev/github/${owner}/${repo}" >/dev/null

post_setup_install_man_pages() {
  echo "Installing manual pages..."
  sudo mkdir -p /usr/local/share/man/man1
  sudo mkdir -p /usr/local/share/man/man5

  scdoc <extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz >/dev/null
  scdoc <extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz >/dev/null
  scdoc <extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz >/dev/null
  scdoc <extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz >/dev/null
}

setup_for_darwin() {
  echo "Installing dependencies..."
  echo 'brew "scdoc"' | brew bundle --file=-

  echo "Building alacritty..."
  make app

  echo "Installing alacritty..."
  sudo cp -f target/release/alacritty /usr/local/bin
  cp -r target/release/osx/Alacritty.app /Applications/

  post_setup_install_man_pages

  echo "Updating terminfo database..."
  tic -xe alacritty,alacritty-direct extra/alacritty.info

  echo "Done!"
}

setup_for_debian() {
  echo "Installing dependencies..."
  sudo apt install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3

  echo "Building alacritty..."
  cargo build --release

  echo "Installing alacritty..."
  sudo cp -f target/release/alacritty /usr/local/bin

  post_setup_install_man_pages

  echo "Adding desktop shortcut..."
  sudo cp -f extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
  sudo desktop-file-install extra/linux/Alacritty.desktop
  sudo update-desktop-database

  echo "Done!"
}

case $OSTYPE in
darwin*)
  setup_for_darwin
  ;;
linux*)
  setup_for_debian
  ;;
*)
  echo "Unknown OS!"
  exit 1
  ;;
esac
