#!/usr/bin/env bash

if type chezmoi >/dev/null 2>&1; then
  echo "Upgrading chezmoi..."
  chezmoi upgrade
else
  echo "Installing chezmoi..."
  curl -sfL https://git.io/chezmoi | sh -s -- -b "${HOME}/.local/bin"
fi

if ! test -L "/usr/local/bin/chezmoi"; then
  echo "Setting up binary: chezmoi"
  sudo ln -nsf "${HOME}/.local/bin/chezmoi" "/usr/local/bin/chezmoi"
fi
