#!/usr/bin/env bash

set -euo pipefail

echo "Updating APT Cache..."
sudo apt-get update

echo "Installing dependencies..."
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

echo "Adding Docker's official GPG key..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

echo "Adding APT Repository..."
codename=$(lsb_release -cs)
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${codename} stable"

echo "Installing Docker..."
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

echo "Setting up for non-root user..."
sudo usermod -aG docker "${USER}"

echo "Installing Docker Compose..."
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

echo "Done!"
