#!/usr/bin/env bash

declare pattern

case $OSTYPE in
  darwin*)
    pattern="_macos_amd64";;
  linux*)
    if test "$(uname -m)" = "aarch64"; then
      go install github.com/cbednarski/hostess@latest
      exit 0
    else
      pattern="_linux_amd64"
    fi
    ;;
  *)
    exit 1;;
esac

filepath=$(download-github-release --repo "cbednarski/hostess" --url-pattern "${pattern}")

echo "Setting up binary: hostess"
chmod u+x "${filepath}"
sudo mv "${filepath}" "/usr/local/bin/hostess"
