#!/usr/bin/env bash

set -euo pipefail

move() {
  local -r src="$1"
  local -r dest="$2"
  local -r dest_dir="$(dirname "$dest")"
  if [ ! -d "${dest_dir}" ]; then
    mkdir -p "${dest_dir}"
  fi
  mv "${src}" "${dest}"
}

setup_for_darwin() {
  echo 'brew "lf"' | brew bundle --file=-
}

setup_for_debian() {
  local -r prefix_path="${HOME}/.local"

  local temp_dir
  temp_dir="$(mktemp --directory /tmp/lf--XXXXXXXXX)"

  cd "${temp_dir}"

  local pattern="*linux-amd64.tar.gz"
  if test "$(uname -m)" = "aarch64"; then
    pattern="*linux-arm64.tar.gz"
  fi

  echo "Downloading archive..."
  gh release download --archive tar.gz --repo gokcehan/lf
  gh release download --repo gokcehan/lf --pattern "${pattern}" -D ./bin

  echo "Extracting archive..."
  tar --strip-component=1 -xzf "${temp_dir}"/*.tar.gz
  tar -xzf "${temp_dir}"/bin/*.tar.gz

  echo "Setting up: lf"
  move ./lf "${prefix_path}/bin/lf"
  move ./lf.1 "${prefix_path}/man/man1/lf.1"
  move ./etc/lf.bash "${prefix_path}/share/bash-completion/completions/lf"
  move ./etc/lf.zsh "${prefix_path}/share/zsh/completions/_lf"

  sudo ln -nsf "${prefix_path}/bin/lf" "/usr/local/bin/lf"

  echo "Cleaning up..."
  rm -rf "${temp_dir}"

  echo "Done!"
}

case "${OSTYPE}" in
darwin*)
  setup_for_darwin
  ;;
linux*)
  setup_for_debian
  ;;
*)
  echo "Unknown OS!"
  exit 1
  ;;
esac
