#!/usr/bin/env bash

if [[ $OSTYPE = darwin* ]]; then
  BINDIR="/usr/local/bin"
else
  BINDIR="${HOME}/.local/bin"
fi

if type chezmoi >/dev/null 2>&1; then
  echo "Upgrading chezmoi..."
  chezmoi upgrade
else
  echo "Installing chezmoi..."
  curl -sfL https://git.io/chezmoi | sh -s -- -b ${BINDIR}
fi

if test "/usr/local/bin/chezmoi" != "${BINDIR}/chezmoi"; then
  echo "Setting up binary: chezmoi"
  sudo ln -nsf ${BINDIR}/chezmoi /usr/local/bin/chezmoi
fi
