#!/usr/bin/env bash

set -euo pipefail

ensure_tool() {
  local -r tool="${1}"
  if ! type "${tool}" >/dev/null 2>&1; then
    echo "missing required tool: ${tool}"
    exit 1
  fi
}

setup_for_darwin() {
  echo "Check https://cloud.google.com/sdk/docs/install#mac"
}

setup_for_debian() {
  ensure_tool curl

  curl --silent https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

  sudo apt-get install --yes google-cloud-cli
}

setup() {
  case $OSTYPE in
    darwin*)
      setup_for_darwin;;
    linux*)
      setup_for_debian;;
    *)
      echo "Unknown OS!"
      exit 1;;
  esac
}

setup
