#!/usr/bin/env bash

# House Keeping
_GIT_DIR="${HOME}/data/gits"
mkdir -p "${_GIT_DIR}"
cd "${_GIT_DIR}"

# Initialization
if [[ ! -d "${_GIT_DIR}/protonvpn-cli" ]]; then
  git clone --depth 1 https://github.com/ProtonVPN/protonvpn-cli
  cd protonvpn-cli
else
  cd protonvpn-cli
  git pull
fi

# Install Dependencies
sudo apt install openvpn dialog

# Installation
sudo ./protonvpn-cli.sh --install
