#!/usr/bin/env bash

set -euo pipefail

setup_for_darwin() {
  echo 'brew "zoxide"' | brew bundle --no-lock --file=-
}

setup_for_debian() {
  local pattern="amd64.deb"
  if test "$(uname -m)" = "aarch64"; then
    pattern="arm64.deb"
  fi

  setup-from-github-release "ajeetdsouza/zoxide" "${pattern}"
}

case $OSTYPE in
  darwin*)
    setup_for_darwin;;
  linux*)
    setup_for_debian;;
  *)
    echo "Unknown OS!"
    exit 1;;
esac
