#!/usr/bin/env bash

# install/update nvm
# https://github.com/nvm-sh/nvm

export NVM_DIR="${NVM_DIR:-"${HOME}/.local/share/nvm"}"

if [[ -d "${NVM_DIR}" ]]; then
  echo "nvm is already installed!"

  cd "${NVM_DIR}"
  if ! [[ -d .git ]]; then
    exit 0
  fi

  echo "Updating nvm..."
  git fetch origin
else
  echo "Installing nvm..."
  git clone https://github.com/nvm-sh/nvm "${NVM_DIR}"
  cd "${NVM_DIR}"
fi

git checkout $(git describe --abbrev=0 --tags --match "v[0-9]*" origin)
