#!/usr/bin/env bash

# install/update hub
# https://github.com/github/hub

echo "Getting the source for hub..."
go get -u github.com/github/hub

cd "${GOPATH}/src/github.com/github/hub"

echo "Building hub from the source..."
make install prefix="${HOME}/.local"

echo "Done!"
