#!/usr/bin/env bash

# House Keeping
_GIT_DIR="${HOME}/data/gits"
mkdir -p "${_GIT_DIR}"
cd "${_GIT_DIR}"

# Initialization
if [[ -d "${_GIT_DIR}/cmusfm" ]]; then
  echo "cmusfm is already installed!"
  echo "Updating cmusfm..."
  cd cmusfm
  git pull
else
  echo "Installing cmusfm..."
  git clone --depth 1 https://github.com/Arkq/cmusfm
  cd cmusfm
fi

echo "Installing dependencies..."
sudo apt install -y automake libcurl4-openssl-dev libnotify-dev

echo "Running build..."
autoreconf --install
rm -rf build && mkdir build && cd build
../configure --prefix="${HOME}/.local" --enable-libnotify
make && make install

echo "Setting up cmusfm binary: cmusfm"
sudo ln -nsf ${HOME}/.local/bin/cmusfm /usr/bin/cmusfm

echo "Done!"
