#!/usr/bin/env bash

set -euo pipefail

command_exists() {
  type "${1}" >/dev/null 2>&1
}

ensure_tool() {
  local -r tool="${1}"
  if ! type "${tool}" >/dev/null 2>&1; then
    echo "missing required tool: ${tool}"
    exit 1
  fi
}

setup_for_darwin() {
  ensure_tool brew

  echo 'brew "ripgrep"' | brew bundle --no-lock --file=-
}

setup_for_debian() {
  if test "$(uname -m)" = "aarch64"; then
    export CARGO_HOME=${CARGO_HOME:-"${HOME}/.local/share/cargo"}
    export RUSTUP_HOME=${RUSTUP_HOME:-"${HOME}/.local/share/rustup"}
    export PATH="${PATH}:${CARGO_HOME}/bin"
    source "${CARGO_HOME}/env"
    cargo install ripgrep
  else
    setup-from-github-release "BurntSushi/ripgrep" "amd64.deb"
  fi
}

setup_ripgrep() {
  case $OSTYPE in
  darwin*)
    setup_for_darwin
    ;;
  linux*)
    if command_exists dpkg; then
      setup_for_debian
    fi
    ;;
  *)
    echo "Unknown OS!"
    exit 1
    ;;
  esac
}

setup_ripgrep
