#!/usr/bin/env bash

# install/update nvm
# https://github.com/creationix/nvm

_nvm_dir="${HOME}/.nvm"
if [[ -d "${_nvm_dir}" ]]; then
  (
    echo "nvm is already installed!"
    echo "Updating nvm..."
    cd "${_nvm_dir}"
    git fetch origin
    git checkout $(git describe --abbrev=0 --tags --match "v[0-9]*" origin)
  ) && source "${_nvm_dir}/nvm.sh"
else
  (
    echo "Installing nvm..."
    git clone https://github.com/creationix/nvm "${_nvm_dir}"
    cd "${_nvm_dir}"
    git checkout $(git describe --abbrev=0 --tags --match "v[0-9]*" origin)
  ) && source "${_nvm_dir}/nvm.sh"
fi

