#!/usr/bin/env bash

set -euo pipefail

declare -r bin_name="git-absorb"
declare -r repo="tummychow/git-absorb"

move() {
  local -r src="$1"
  local -r dest="$2"
  local -r dest_dir="$(dirname "$dest")"
  if [ ! -d "${dest_dir}" ]; then
    mkdir -p "${dest_dir}"
  fi
  mv "${src}" "${dest}"
}

setup_for_debian() {
  declare -r prefix_path="${HOME}/.local"

  declare temp_dir
  temp_dir="$(mktemp --directory /tmp/${bin_name}--XXXXXXXXX)"

  cd "${temp_dir}"

  declare pattern="*x86_64-unknown-linux-musl.tar.gz"
  if test "$(uname -m)" = "aarch64"; then
    echo "Unsupported arch!"
    exit 1
  fi

  echo "Downloading archive..."
  gh release download --repo "${repo}" --pattern "${pattern}"

  echo "Extracting archive..."
  tar --strip-component=1 -xzf "${temp_dir}"/*.tar.gz

  echo "Setting up: ${bin_name}"
  move ./${bin_name} "${prefix_path}/bin/${bin_name}"
  move ./doc/${bin_name}.1 "${prefix_path}/man/man1/${bin_name}.1"

  echo "Cleaning up..."
  rm -rf "${temp_dir}"

  echo "Done!"
}

case "${OSTYPE}" in
  linux*)
    setup_for_debian;;
  *)
    echo "Unknown OS!"
    exit 1;;
esac
