#!/usr/bin/env bash

set -euo pipefail

get_latest_reposiotry() {
  local -r repo_uri="${1}"
  local -r repo_dir="${2}"

  echo "Repository URI: ${repo_uri}"
  if [[ ! -d "${repo_dir}" ]]; then
    echo "Cloning repository..."
    mkdir -p "$(dirname "${repo_dir}")"
    git clone --quiet --recursive "${repo_uri}" "${repo_dir}"
    pushd "${repo_dir}" >/dev/null
  else
    echo "Pulling latest commits..."
    pushd "${repo_dir}" >/dev/null
    git pull
    git submodule update --init
  fi

  popd >/dev/null
}

setup_for_darwin() {
  if test -z "$(brew list | grep tmux)"; then
    brew install --HEAD tmux
  else
    brew reinstall tmux
  fi
}

setup_for_debian() {
  local -r owner="tmux"
  local -r repo="tmux"

  get_latest_reposiotry "https://github.com/${owner}/${repo}" "${HOME}/Dev/github/${owner}/${repo}"
  pushd "${HOME}/Dev/github/${owner}/${repo}" >/dev/null

  echo "Installing dependencies..."
  sudo apt install -y libevent-dev ncurses-dev build-essential bison pkg-config

  echo "Running build..."
  sh autogen.sh
  ./configure --enable-sixel --prefix="${HOME}/.local"
  make
  make install

  echo "Setting up binary: tmux"
  sudo ln -nsf "${HOME}/.local/bin/tmux" /usr/local/bin/tmux

  echo "Done!"
}

setup() {
  case "${OSTYPE}" in
  darwin*)
    setup_for_darwin
    ;;
  linux*)
    setup_for_debian
    ;;
  *)
    echo "Unknown OS!"
    exit 1
    ;;
  esac
}

setup
