#!/usr/bin/env bash

# House Keeping
_deezer_dir="${HOME}/Music/Downloads/Deezer"
if [[ ! -d "${_deezer_dir}" ]]; then
  mkdir -p ${_deezer_dir}
fi
cd ${_deezer_dir}

_smloadr_dir="${_deezer_dir}/smloadr"
if [[ -d "${_smloadr_dir}" ]]; then
  echo "SMLoadr is already installed!"
  echo "Updating to the latest version..."
  cd ${_smloadr_dir}
  git pull
else
  echo "Installing SMLoadr..."
  git clone --depth 1 https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr.git ${_smloadr_dir}
  cd ${_smloadr_dir}
fi

echo "Installing dependencies..."
npm install

echo "Setting up SMLoadr binary: smloadr"
_smloadr_bin="${_deezer_dir}/smloadr.sh"
tee ${_smloadr_bin} > /dev/null << EOL
#!/usr/bin/env sh

cd ${_deezer_dir}
node ${_smloadr_dir}/SMLoadr.js \${@}
EOL
chmod u+x ${_smloadr_bin}
ln -sf ${_smloadr_bin} ${HOME}/.local/bin/smloadr

echo "Done!"
