#!/usr/bin/env bash

set -eu

get_latest_reposiotry() {
  local repo_uri="${1}"
  local repo_dir="${2}"

  echo "Repository URI: ${repo_uri}"
  if [[ ! -d "${repo_dir}" ]]; then
    echo "Cloning repository..."
    mkdir -p "$(dirname "${repo_dir}")"
    git clone --quiet --recursive "${repo_uri}" "${repo_dir}"
    pushd "${repo_dir}" >/dev/null
  else
    echo "Pulling latest commits..."
    pushd "${repo_dir}" >/dev/null
    git pull
    git submodule update --init
  fi

  popd >/dev/null
}

declare -r owner="alacritty"
declare -r repo="alacritty"

get_latest_reposiotry "https://github.com/${owner}/${repo}" "${HOME}/Dev/github/${owner}/${repo}"
pushd "${HOME}/Dev/github/${owner}/${repo}" >/dev/null

echo "Installing dependencies..."

sudo apt install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3

echo "Building alacritty..."

cargo build --release

echo "Installing alacritty..."

sudo cp -f target/release/alacritty /usr/local/bin
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

sudo mkdir -p /usr/local/share/man/man1
gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null

echo "Done!"
