#!/usr/bin/env bash

set -euo pipefail

ensure_tool() {
  local -r tool="${1}"
  if ! type "${tool}" >/dev/null 2>&1; then
    echo "missing required tool: ${tool}"
    exit 1
  fi
}

setup_for_darwin() {
  ensure_tool brew

  brew install bat
}

setup_for_debian() {
  ensure_tool dpkg
  ensure_tool gh

  local -r temp_dir="$(mktemp --directory /tmp/bat--XXXXXXXXX)"
  gh release download "${latest_tag}" --repo "sharkdp/bat" --pattern "*musl*amd64.deb" --dir "${temp_dir}"
  sudo dpkg --install ${temp_dir}/bat*amd64.deb
}

setup_bat() {
  case $OSTYPE in
    darwin*)
      setup_for_darwin;;
    linux*)
      setup_for_debian;;
    *)
      echo "Unknown OS!"
      exit 1;;
  esac
}

setup_bat
