#!/usr/bin/env bash

# install/update hub
# https://github.com/github/hub

echo "Installing hub..."

echo "Getting the source..."
go get -u github.com/github/hub

echo "Running build..."
cd "${GOPATH}/src/github.com/github/hub"
make install prefix="${HOME}/.local"

echo "Done!"
