#!/usr/bin/env bash

cd /tmp || exit

echo "Downloading Postman Source Archive..."
wget -q https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
tar -xzf postman.tar.gz
rm postman.tar.gz

echo "Installing to /opt/Postman Directory..."
if [ -d "/opt/Postman" ]; then
  sudo rm -rf /opt/Postman
fi
sudo mv Postman /opt/Postman

echo "Creating Symbolic Link..."
if [ -L "/usr/bin/postman" ]; then
  sudo rm -f /usr/bin/postman
fi
sudo ln -s /opt/Postman/Postman /usr/bin/postman

echo "Adding Application Shortcut..."
cat > ${HOME}/.local/share/applications/postman.desktop <<EOL
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=postman
Icon=/opt/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
EOL

echo "Done!"
