#!/usr/bin/env bash

cd /tmp || exit

echo "Installing Postman..."
_postman_url="https://dl.pstmn.io/download/latest/linux64"
_postman_dir="/opt/Postman"

echo "Downloading Source Archive..."
wget -q --show-progress ${_postman_url} -O postman.tar.gz
tar -xzf postman.tar.gz
rm postman.tar.gz

echo "Installation Directory: ${_postman_dir}"
if [[ -d "${_postman_dir}" ]]; then
  sudo rm -rf ${_postman_dir}
fi
sudo mv Postman ${_postman_dir}

echo "Setting up Postman binary: postman"
sudo ln -nsf ${_postman_dir}/Postman /usr/local/bin/postman

echo "Adding Application Shortcut..."
cat > ${HOME}/.local/share/applications/postman.desktop <<EOL
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=postman
Icon=${_postman_dir}/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
EOL

echo "Done!"
