#!/usr/bin/env bash

set -e

function setup-git-credential-libsecret() {
  echo "Installing dependencies..."
  sudo apt install libsecret-1-dev libglib2.0-dev

  echo "Running build..."
  cd "/usr/share/doc/git/contrib/credential/libsecret"
  sudo make

  local -r helper="/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret"

  echo "Updating git config..."
  git config --global credential.helper "${helper}"

  echo "Done!"
}

setup-git-credential-libsecret
